from dotenv import load_dotenv
import os

load_dotenv()

IMAGE_HEIGHT = os.getenv('SCREENSHOT_HEIGHT')
IMAGE_WIDTH = os.getenv('SCREENSHOT_WIDTH')
IMAGE_PERCENTAGE = os.getenv('PERCENTAGE_SCREEN')
SCREENSHOT_OPTION = os.getenv('SCREENSHOT_OPTION')
VIDEO_RECORDING = os.getenv('VIDEO_RECORDING')
VIDEO_WIDTH = os.getenv('VIDEO_WIDTH')
VIDEO_HEIGHT = os.getenv('VIDEO_HEIGHT')
VIDEO_FRAME_RATE = os.getenv('VIDEO_FRAME_RATE')
VIDEO_RESIZE_PERCENTAGE = os.getenv('VIDEO_RESIZE_PERCENTAGE')
