name: tests for plugin
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

# S3 structure
# | ${{ github.repository }}
# |___history: contains historical data for trend + graphs
# |___1/reports
# |___2/reports
# ...

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        pip install -r tests/requirements.txt
    - name: install python 3.9
      run: |
        apt update
        apt install software-properties-common
        add-apt-repository ppa:deadsnakes/ppa
        apt install python3.9
        python -V
        python3.9 -V

    - name: install allure
      run: |
        curl -o allure-2.19.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.tgz
        tar -zxvf allure-2.19.0.tgz -C /opt/
        chmod +x /opt/allure-2.19.0/bin/allure
        /opt/allure-2.19.0/bin/allure --version

    - name: run tests
      run: |
        tests/run.sh
