name: tests for plugin
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: test
      run: |
        export CHROMEWEBDRIVER=$CHROMEWEBDRIVER/chromedriver
        ls -l $CHROMEWEBDRIVER
#        echo $CHROMEWEBDRIVER
#        ls -l $CHROMEWEBDRIVER
#        cp $CHROMEWEBDRIVER /usr/bin
#        export CHROMEWEBDRIVER=/usr/bin/chromedriver
#        ls -l $CHROMEWEBDRIVER
#        ls -l /usr/bin/chromedriver

    - name: run tests
      run: |
        tests/run.sh
