name: tests for plugin
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        python3.9 -m pip install -r tests/requirements.txt

    - name: run tests
      run: |
        tests/run.sh
