  name: basic workflow testing
  on:
    workflow_dispatch:
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      
#      - name: install dependencies
#        run: |
#          pip install -r requirements.txt && touch a.txt
#
#      - name: download report from s3
#        uses: keithweaver/aws-s3-github-action@v1.0.0
#        with:
#          command: cp
#          source: ${{ secrets.AWS_BUCKET }}
#          destination: a
#          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: run tests
#        run: |
#          pytest --driver Chrome --alluredir=reports --driver-path deb/chromedriver

      - name: download
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://np-allure-reports/a.png
          destination: .
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: list
        run: |
          ls -lahG
