name: tests for plugin
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        pip install -r tests/requirements.txt

    - run: |
        ls -l /usr/local/share/chrome_driver
        export CHROMEDRIVER=/usr/local/share/chrome_driver
        cp /usr/local/share/chrome_driver /usr/local/share/chromedriver
        ls -l /usr/local/share/chromedriver
        chmod +x /usr/local/share/chromedriver

    - name: run tests
      run: |
        tests/run.sh
