name: tests for plugin

on:
  pull_request:
    branches:
      - main
      - release*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd tests
        pip install -r ./test-reqs.txt
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pytest-enhanced-reports

    - name: Basic tests
      run: |
        cd tests
        ./run.sh
